import { S, save } from '../state/index.js';
import { toast, infoBtn, infoPop } from '../components/index.js';

const CARD  = 'background:#fff;border:0.5px solid #e2e8f0;border-radius:12px;padding:20px 22px;margin-bottom:14px;';
const LABEL = 'display:block;font-size:11px;color:#94a3b8;margin-bottom:5px;';
const GRID2 = 'display:grid;grid-template-columns:1fr 1fr;gap:14px;';
const GRID3 = 'display:grid;grid-template-columns:1fr 1fr 1fr;gap:14px;';

function field(labelText, inputHtml) {
  return `<div><label style="${LABEL}">${labelText}</label>${inputHtml}</div>`;
}

export function screen() {
  const f          = S.firm || {};
  const isComplete = !!(f.name && f.abn && f.principal && f.email);

  return `<div style="max-width:680px;">

    <!-- HEADER -->
    <div style="display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:24px;">
      <div>
        <h1 style="font-size:20px;font-weight:500;color:#0f172a;margin-bottom:3px;">Firm Profile</h1>
        <p style="font-size:13px;color:#64748b;">Practice identity and contact details for AUSTRAC and compliance reporting.</p>
      </div>
      ${isComplete
        ? `<span style="font-size:11px;font-weight:500;padding:3px 10px;border-radius:99px;background:#f0fdf4;color:#166534;border:0.5px solid #bbf7d0;white-space:nowrap;">Complete</span>`
        : `<span style="font-size:11px;font-weight:500;padding:3px 10px;border-radius:99px;background:#f8fafc;color:#94a3b8;border:0.5px solid #e2e8f0;white-space:nowrap;">Incomplete</span>`}
    </div>

    <!-- PRACTICE IDENTITY -->
    <div style="${CARD}">
      <div style="display:flex;align-items:center;gap:6px;margin-bottom:16px;">
        <span style="font-size:13px;font-weight:500;color:#0f172a;">Practice identity</span>
        ${infoBtn('firm-practice-tip')}
      </div>
      ${infoPop('firm-practice-tip', `
        <strong class="text-indigo-300 block mb-2">Why AUSTRAC needs your practice details</strong>
        <p>AUSTRAC and any independent evaluator must be able to clearly identify your firm and know who is ultimately responsible for AML/CTF compliance.</p>
        <p class="mt-2">In the event of an audit, these details establish which legal entity is the reporting entity, how to contact the firm, and who the accountable person is.</p>
        <p class="mt-2 text-slate-400 border-t border-slate-600 pt-2">These details appear on every compliance report generated by SimpleAML and must be kept current.</p>`)}
      <div style="margin-bottom:14px;">
        ${field('Firm name *', `<input id="fp-name" type="text" class="inp" value="${f.name||''}" placeholder="e.g. Smith &amp; Associates">`)}
      </div>
      <div style="${GRID3}">
        ${field('ABN *',         `<input id="fp-abn"  type="text" class="inp" value="${f.abn||''}"  placeholder="12 345 678 901">`)}
        ${field('ACN',           `<input id="fp-acn"  type="text" class="inp" value="${f.acn||''}"  placeholder="Optional">`)}
        ${field('Practice type', `<select id="fp-type" class="inp">${['Sole Practitioner','Partnership','Pty Ltd','Trust','Other'].map(o=>`<option ${f.type===o?'selected':''}>${o}</option>`).join('')}</select>`)}
      </div>
    </div>

    <!-- PRACTICE ADDRESS -->
    <div style="${CARD}">
      <div style="font-size:13px;font-weight:500;color:#0f172a;margin-bottom:16px;">Practice address</div>
      <div style="margin-bottom:14px;">
        ${field('Street address', `<input id="fp-address" type="text" class="inp" value="${f.address||''}" placeholder="Level 2, 123 Collins St">`)}
      </div>
      <div style="${GRID3}">
        ${field('Suburb',   `<input id="fp-suburb"   type="text" class="inp" value="${f.suburb||''}"   placeholder="Melbourne">`)}
        ${field('State',    `<select id="fp-state" class="inp"><option value="">— Select —</option>${['NSW','VIC','QLD','WA','SA','TAS','ACT','NT'].map(o=>`<option ${f.state===o?'selected':''}>${o}</option>`).join('')}</select>`)}
        ${field('Postcode', `<input id="fp-postcode" type="text" class="inp" value="${f.postcode||''}" placeholder="3000">`)}
      </div>
    </div>

    <!-- PRINCIPAL CONTACT -->
    <div style="${CARD}">
      <div style="font-size:13px;font-weight:500;color:#0f172a;margin-bottom:16px;">Principal contact</div>
      <div style="${GRID2}">
        ${field('Full name *', `<input id="fp-principal" type="text"  class="inp" value="${f.principal||''}" placeholder="Jane Smith">`)}
        ${field('Position',    `<input id="fp-position"  type="text"  class="inp" value="${f.position||''}"  placeholder="Principal / Managing Partner">`)}
        ${field('Email *',     `<input id="fp-email"     type="email" class="inp" value="${f.email||''}"     placeholder="jane@firm.com.au">`)}
        ${field('Phone',       `<input id="fp-phone"     type="tel"   class="inp" value="${f.phone||''}"     placeholder="03 9123 4567">`)}
      </div>
    </div>

    <!-- SAVE / POST-SAVE NAV -->
    ${f.savedDate ? `
    <div style="background:#f8fafc;border:0.5px solid #e2e8f0;border-radius:12px;padding:16px 20px;margin-bottom:14px;">
      <div style="font-size:12px;font-weight:500;color:#0f172a;margin-bottom:12px;">Firm Profile saved — what would you like to do next?</div>
      <div style="display:flex;flex-direction:column;gap:8px;">
        <button onclick="saveFirmDetails();go('firm-appointments')" style="font-size:12px;font-weight:500;color:#fff;background:#4f46e5;border:none;padding:9px 16px;border-radius:8px;cursor:pointer;text-align:center;">Save &amp; continue to Appointments →</button>
        <button onclick="saveFirmDetails();go('home')" style="font-size:12px;color:#64748b;background:#fff;border:0.5px solid #e2e8f0;padding:9px 16px;border-radius:8px;cursor:pointer;text-align:center;">Save &amp; return to Home</button>
      </div>
    </div>` : `
    <button onclick="saveFirmDetails()" style="width:100%;font-size:13px;font-weight:500;color:#fff;background:#4f46e5;border:none;padding:11px 16px;border-radius:8px;cursor:pointer;">Save Firm Profile</button>`}

    ${f.savedDate ? `<p style="font-size:11px;color:#94a3b8;text-align:center;">Last saved: ${new Date(f.savedDate).toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric'})}</p>` : ''}

  </div>`;
}

// ─── ACTIONS ──────────────────────────────────────────────────────────────────
window.saveFirmDetails = function() {
  const name = document.getElementById('fp-name')?.value?.trim();
  if (!name) { toast('Firm name is required', 'err'); return; }
  const email = document.getElementById('fp-email')?.value?.trim();
  if (email && !email.includes('@')) { toast('Email address must contain @', 'err'); return; }
  const isFirstSave = !S.firm.newsletterShown;
  const existingAppt = S.firm.appt || {};
  S.firm = {
    ...S.firm,
    name,
    abn:       document.getElementById('fp-abn')?.value||'',
    acn:       document.getElementById('fp-acn')?.value||'',
    type:      document.getElementById('fp-type')?.value||'',
    address:   document.getElementById('fp-address')?.value||'',
    suburb:    document.getElementById('fp-suburb')?.value||'',
    state:     document.getElementById('fp-state')?.value||'',
    postcode:  document.getElementById('fp-postcode')?.value||'',
    principal: document.getElementById('fp-principal')?.value||'',
    position:  document.getElementById('fp-position')?.value||'',
    email:     email||'',
    phone:     document.getElementById('fp-phone')?.value||'',
    appt:      existingAppt,
    savedDate: new Date().toISOString().split('T')[0],
  };
  save();
  toast('Firm Profile saved');
  if (isFirstSave && typeof window.showNewsletterModal === 'function') {
    setTimeout(function() { window.showNewsletterModal(); }, 400);
  }
  go('firm-details');
};
