import { S, save } from '../state/index.js';
import { toast } from '../components/index.js';

export function screen() {
  const f = S.firm;
  return `
    <div class="p-8 max-w-2xl space-y-6">
      <div><h1 class="text-2xl font-bold">Firm Profile</h1><p class="text-slate-400 text-sm mt-1">Your practice details and compliance appointments.</p></div>
      <div class="bg-blue-50 border border-blue-100 rounded-xl p-4 text-xs text-blue-700">These details appear on your compliance report. This is <strong>not</strong> your AUSTRAC enrolment — that is completed separately in Step 6.</div>

      <div class="bg-white border rounded-xl p-5 space-y-4">
        <div class="flex items-center gap-2">
          <h2 class="text-xs font-bold text-slate-400 uppercase tracking-widest">Practice details</h2>
          <button type="button" onclick="var t=document.getElementById('firm-practice-tip');t.style.display=t.style.display==='block'?'none':'block'" class="inline-flex items-center justify-center w-4 h-4 rounded-full bg-indigo-500 text-white text-[9px] font-bold cursor-pointer flex-shrink-0 hover:bg-indigo-600">i</button>
        </div>
        <div id="firm-practice-tip" style="display:none" class="bg-slate-800 text-slate-200 rounded-xl p-4 text-xs leading-relaxed space-y-2">
          <div class="font-bold text-indigo-300">Why AUSTRAC needs your practice details</div>
          <p>AUSTRAC and any independent evaluator must be able to clearly identify your firm and know who is ultimately responsible for AML/CTF compliance. Your firm name, ABN, address, and principal contact are the foundation of your compliance record.</p>
          <p>In the event of an audit, inspection, or enforcement action, these details establish: <strong class="text-white">(1)</strong> which legal entity is the reporting entity, <strong class="text-white">(2)</strong> how to contact the firm, and <strong class="text-white">(3)</strong> who the accountable person is.</p>
          <p class="text-slate-400 border-t border-slate-600 pt-2">These details appear on every compliance report generated by SimpleAML and must be kept current.</p>
        </div>
        <div class="grid grid-cols-2 gap-3">
          <div><label class="text-xs text-slate-500">Firm name *</label><input id="fp-name" type="text" class="inp" value="${f.name||''}" placeholder="e.g. Smith & Associates"></div>
          <div><label class="text-xs text-slate-500">ABN *</label><input id="fp-abn" type="text" class="inp" value="${f.abn||''}" placeholder="12 345 678 901"></div>
          <div><label class="text-xs text-slate-500">ACN</label><input id="fp-acn" type="text" class="inp" value="${f.acn||''}" placeholder="Optional"></div>
          <div><label class="text-xs text-slate-500">Practice type</label>
            <select id="fp-type" class="inp">
              ${['Sole Practitioner','Partnership','Pty Ltd','Trust','Other'].map(o=>`<option ${f.type===o?'selected':''}>${o}</option>`).join('')}
            </select>
          </div>
        </div>
        <div class="grid grid-cols-2 gap-3">
          <div class="col-span-2"><label class="text-xs text-slate-500">Street address</label><input id="fp-address" type="text" class="inp" value="${f.address||''}" placeholder="Level 2, 123 Collins St"></div>
          <div><label class="text-xs text-slate-500">Suburb</label><input id="fp-suburb" type="text" class="inp" value="${f.suburb||''}" placeholder="Melbourne"></div>
          <div><label class="text-xs text-slate-500">State</label>
            <select id="fp-state" class="inp">
              <option value="">— Select —</option>
              ${['NSW','VIC','QLD','WA','SA','TAS','ACT','NT'].map(o=>`<option ${f.state===o?'selected':''}>${o}</option>`).join('')}
            </select>
          </div>
        </div>
      </div>

      <div class="bg-white border rounded-xl p-5 space-y-4">
        <div class="flex items-center justify-between">
          <h2 class="text-xs font-bold text-slate-400 uppercase tracking-widest">Principal contact
            <span class="normal-case font-normal text-slate-400 ml-2">— AUSTRAC requires a clearly identified responsible person</span>
          </h2>
        </div>
        <div class="grid grid-cols-2 gap-3">
          <div><label class="text-xs text-slate-500">Full name *</label><input id="fp-principal" type="text" class="inp" value="${f.principal||''}" placeholder="Jane Smith"></div>
          <div><label class="text-xs text-slate-500">Position</label><input id="fp-position" type="text" class="inp" value="${f.position||''}" placeholder="Principal / Managing Partner"></div>
          <div><label class="text-xs text-slate-500">Email *</label><input id="fp-email" type="email" class="inp" value="${f.email||''}" placeholder="jane@firm.com.au"></div>
          <div><label class="text-xs text-slate-500">Phone</label><input id="fp-phone" type="tel" class="inp" value="${f.phone||''}" placeholder="03 9123 4567"></div>
        </div>
      </div>

      <div class="bg-white border rounded-xl p-5 space-y-4">
        <div class="flex items-center gap-2">
          <h2 class="text-xs font-bold text-slate-400 uppercase tracking-widest">Compliance appointments</h2>
          <button type="button" onclick="var t=document.getElementById('firm-appt-tip');t.style.display=t.style.display==='block'?'none':'block'" class="inline-flex items-center justify-center w-4 h-4 rounded-full bg-indigo-500 text-white text-[9px] font-bold cursor-pointer flex-shrink-0 hover:bg-indigo-600">i</button>
        </div>
        <div id="firm-appt-tip" style="display:none" class="bg-slate-800 text-slate-200 rounded-xl p-4 text-xs leading-relaxed space-y-2">
          <div class="font-bold text-indigo-300">Why compliance appointments must be recorded</div>
          <p>AUSTRAC requires every reporting entity to formally designate who holds each compliance role. These appointments are not just administrative — they establish <strong class="text-white">personal accountability</strong>. If something goes wrong, AUSTRAC and any court need to know exactly which individual was responsible for each function.</p>
          <ul class="space-y-1 pl-1">
            <li>· <strong class="text-white">AMLCO</strong> — your primary regulatory contact and the person AUSTRAC will deal with directly</li>
            <li>· <strong class="text-white">Reporting Officer</strong> — responsible for filing Suspicious Matter Reports and Threshold Transaction Reports</li>
            <li>· <strong class="text-white">Senior Manager</strong> — must approve the AML/CTF Program; cannot be delegated below this level</li>
            <li>· <strong class="text-white">Principal / Managing Partner</strong> — carries ultimate firm-level accountability</li>
          </ul>
          <p class="text-slate-400 border-t border-slate-600 pt-2">Even if one person holds every role — common in sole practices — each must be formally recorded. A register that shows one person across all roles is compliant. A register with blank appointments is not.</p>
        </div>
        <p class="text-xs text-slate-400 leading-relaxed">Every firm must formally record who holds each compliance role — even if one person holds all of them. This creates a clear accountability trail that AUSTRAC requires.</p>
        <div class="bg-amber-50 border border-amber-200 rounded-xl p-4">
          <div class="text-xs font-bold text-amber-800 mb-1">Sole practitioner?</div>
          <p class="text-xs text-amber-700 mb-3 leading-relaxed">If you run the practice alone, you hold all roles. Enter your name once below and click the button to fill every position automatically.</p>
          <div class="flex items-center gap-2">
            <input id="sole-name" type="text" class="inp flex-1 text-sm" placeholder="Your full legal name">
            <button onclick="fillAllRoles()" class="text-xs bg-amber-500 text-white px-4 py-2 rounded-lg font-semibold hover:bg-amber-600 transition whitespace-nowrap">Auto-fill all roles →</button>
          </div>
        </div>
        ${[
          ['amlco','AML/CTF Compliance Officer (AMLCO)','Primary regulatory liaison. Must be appointed before enrolment.'],
          ['reporting','Reporting Officer','Responsible for filing SMRs and TTRs with AUSTRAC.'],
          ['senior','Senior Manager','Approves the AML/CTF Program.'],
          ['principal2','Principal / Managing Partner','Overall firm leadership accountability.'],
          ['delegate','Delegate (optional)','For larger firms where compliance tasks are formally delegated.'],
        ].map(([key,title,desc])=>`
          <div class="border rounded-lg p-3 space-y-2">
            <div class="text-sm font-semibold">${title}</div>
            <div class="text-xs text-slate-400">${desc}</div>
            <div class="grid grid-cols-2 gap-2">
              <div><label class="text-xs text-slate-500">Full name</label><input id="appt-${key}-name" type="text" class="inp" value="${(f.appt||{})[key]?.name||''}"></div>
              <div><label class="text-xs text-slate-500">Date appointed</label><input id="appt-${key}-date" type="date" class="inp" value="${(f.appt||{})[key]?.date||''}"></div>
            </div>
          </div>`).join('')}
      </div>
      <button onclick="saveFirm()" class="w-full bg-indigo-600 text-white py-3 rounded-xl font-semibold hover:bg-indigo-700 transition">Save Firm Profile</button>
    </div>`;
}

// ─── ACTIONS ──────────────────────────────────────────────────────────────────
window.fillAllRoles = function() {
  const name = document.getElementById('sole-name')?.value?.trim();
  if (!name) { toast('Enter your name first', 'err'); return; }
  ['amlco','reporting','senior','principal2','delegate'].forEach(k => {
    const el = document.getElementById(`appt-${k}-name`);
    if (el) el.value = name;
  });

window.saveFirm = function() {
  const name = document.getElementById('fp-name')?.value?.trim();
  if (!name) { toast('Firm name is required', 'err'); return; }
  S.firm = {
    name, abn: document.getElementById('fp-abn')?.value||'',
    acn: document.getElementById('fp-acn')?.value||'',
    type: document.getElementById('fp-type')?.value||'',
    address: document.getElementById('fp-address')?.value||'',
    suburb: document.getElementById('fp-suburb')?.value||'',
    state: document.getElementById('fp-state')?.value||'',
    principal: document.getElementById('fp-principal')?.value||'',
    position: document.getElementById('fp-position')?.value||'',
    email: document.getElementById('fp-email')?.value||'',
    phone: document.getElementById('fp-phone')?.value||'',
    appt: {}
  };
  ['amlco','reporting','senior','principal2','delegate'].forEach(k => {
    S.firm.appt[k] = {
      name: document.getElementById(`appt-${k}-name`)?.value||'',
      date: document.getElementById(`appt-${k}-date`)?.value||''
    };
  });
  save(); toast('Firm profile saved'); go('dashboard');
};
