import { S, save } from '../state/index.js';
import { toast, infoBtn, infoPop } from '../components/index.js';

export function screen() {
  const f = S.firm;
  const isComplete = Object.keys(f).length > 2 && !!(f.name && f.abn && f.principal && f.email);
  const badge = isComplete
    ? '<span class="inline-flex items-center gap-1 text-xs font-semibold px-3 py-1 rounded-full bg-green-100 text-green-700">✓ Complete</span>'
    : '<span class="inline-flex items-center gap-1 text-xs font-semibold px-3 py-1 rounded-full bg-slate-100 text-slate-500">⚠ Incomplete</span>';

  return `
    <div class="py-8 space-y-8">

      <!-- HEADER -->
      <div class="flex items-start justify-between">
        <div>
          <h1 class="text-2xl font-bold text-slate-900">Firm Profile</h1>
          <p class="text-sm text-slate-400 mt-1">Responsible persons and practice identity for AML/CTF purposes</p>
        </div>
        ${badge}
      </div>

      <!-- PRACTICE IDENTITY -->
      <div class="bg-white border border-slate-200 rounded-xl p-6 space-y-5">
        <div class="flex items-center gap-2">
          <h2 class="text-sm font-bold text-slate-700">Practice Identity</h2>
          ${infoBtn('firm-practice-tip')}
        </div>
        ${infoPop('firm-practice-tip', `<strong class="text-indigo-300 block mb-2">Why AUSTRAC needs your practice details</strong>
          <p>AUSTRAC and any independent evaluator must be able to clearly identify your firm and know who is ultimately responsible for AML/CTF compliance. Your firm name, ABN, address, and principal contact are the foundation of your compliance record.</p>
          <p class="mt-2">In the event of an audit, inspection, or enforcement action, these details establish: <strong class="text-white">(1)</strong> which legal entity is the reporting entity, <strong class="text-white">(2)</strong> how to contact the firm, and <strong class="text-white">(3)</strong> who the accountable person is.</p>
          <p class="mt-2 text-slate-400 border-t border-slate-600 pt-2">These details appear on every compliance report generated by SimpleAML and must be kept current.</p>`)}
        <div class="space-y-4">
          <div><label class="text-xs text-slate-500">Firm name *</label><input id="fp-name" type="text" class="inp mt-1" value="${f.name||''}" placeholder="e.g. Smith & Associates"></div>
          <div class="grid grid-cols-3 gap-4">
            <div><label class="text-xs text-slate-500">ABN *</label><input id="fp-abn" type="text" class="inp mt-1" value="${f.abn||''}" placeholder="12 345 678 901"></div>
            <div><label class="text-xs text-slate-500">ACN</label><input id="fp-acn" type="text" class="inp mt-1" value="${f.acn||''}" placeholder="Optional"></div>
            <div><label class="text-xs text-slate-500">Practice type</label>
              <select id="fp-type" class="inp mt-1">
                ${['Sole Practitioner','Partnership','Pty Ltd','Trust','Other'].map(o=>`<option ${f.type===o?'selected':''}>${o}</option>`).join('')}
              </select>
            </div>
          </div>
        </div>
      </div>

      <!-- PRACTICE ADDRESS -->
      <div class="bg-white border border-slate-200 rounded-xl p-6 space-y-5">
        <h2 class="text-sm font-bold text-slate-700">Practice Address</h2>
        <div class="space-y-4">
          <div><label class="text-xs text-slate-500">Street address</label><input id="fp-address" type="text" class="inp mt-1" value="${f.address||''}" placeholder="Level 2, 123 Collins St"></div>
          <div class="grid grid-cols-3 gap-4">
            <div><label class="text-xs text-slate-500">Suburb</label><input id="fp-suburb" type="text" class="inp mt-1" value="${f.suburb||''}" placeholder="Melbourne"></div>
            <div><label class="text-xs text-slate-500">State</label>
              <select id="fp-state" class="inp mt-1">
                <option value="">— Select —</option>
                ${['NSW','VIC','QLD','WA','SA','TAS','ACT','NT'].map(o=>`<option ${f.state===o?'selected':''}>${o}</option>`).join('')}
              </select>
            </div>
            <div><label class="text-xs text-slate-500">Postcode</label><input id="fp-postcode" type="text" class="inp mt-1" value="${f.postcode||''}" placeholder="3000"></div>
          </div>
        </div>
      </div>

      <!-- PRINCIPAL CONTACT -->
      <div class="bg-white border border-slate-200 rounded-xl p-6 space-y-5">
        <h2 class="text-sm font-bold text-slate-700">Principal Contact</h2>
        <div class="grid grid-cols-2 gap-4">
          <div><label class="text-xs text-slate-500">Full name *</label><input id="fp-principal" type="text" class="inp mt-1" value="${f.principal||''}" placeholder="Jane Smith"></div>
          <div><label class="text-xs text-slate-500">Position</label><input id="fp-position" type="text" class="inp mt-1" value="${f.position||''}" placeholder="Principal / Managing Partner"></div>
          <div><label class="text-xs text-slate-500">Email *</label><input id="fp-email" type="email" class="inp mt-1" value="${f.email||''}" placeholder="jane@firm.com.au"></div>
          <div><label class="text-xs text-slate-500">Phone</label><input id="fp-phone" type="tel" class="inp mt-1" value="${f.phone||''}" placeholder="03 9123 4567"></div>
        </div>
      </div>

      <!-- RESPONSIBLE PERSONS -->
      <div class="bg-white border border-slate-200 rounded-xl p-6 space-y-5">
        <div class="flex items-center gap-2">
          <h2 class="text-sm font-bold text-slate-700">Responsible Persons <span class="font-normal text-slate-400">— required by AUSTRAC</span></h2>
          ${infoBtn('firm-appt-tip')}
        </div>
        ${infoPop('firm-appt-tip', `<strong class="text-indigo-300 block mb-2">Why compliance appointments must be recorded</strong>
          <p>AUSTRAC requires every reporting entity to formally designate who holds each compliance role. These appointments establish <strong class="text-white">personal accountability</strong>.</p>
          <ul class="mt-2 space-y-1 pl-1">
            <li>· <strong class="text-white">AMLCO</strong> — your primary regulatory contact</li>
            <li>· <strong class="text-white">Reporting Officer</strong> — responsible for filing SMRs and TTRs</li>
            <li>· <strong class="text-white">Senior Manager</strong> — must approve the AML/CTF Program</li>
            <li>· <strong class="text-white">Principal / Managing Partner</strong> — carries ultimate firm-level accountability</li>
          </ul>
          <p class="mt-2 text-slate-400 border-t border-slate-600 pt-2">Even if one person holds every role, each must be formally recorded.</p>`)}

        <div class="bg-slate-50 border border-slate-200 rounded-xl p-4">
          <p class="text-xs text-slate-500 mb-3">Sole practitioner? Enter your name once and auto-fill all roles.</p>
          <div class="flex items-center gap-2">
            <input id="sole-name" type="text" class="inp flex-1 text-sm" placeholder="Your full legal name">
            <button onclick="fillAllRoles()" class="text-xs bg-slate-700 text-white px-4 py-2 rounded-lg font-semibold hover:bg-slate-800 transition whitespace-nowrap">Auto-fill all roles →</button>
          </div>
        </div>

        <div class="space-y-3">
          ${[
            ['amlco','AML/CTF Compliance Officer (AMLCO)','Primary regulatory liaison. Must be appointed before enrolment.'],
            ['reporting','Reporting Officer','Responsible for filing SMRs and TTRs with AUSTRAC.'],
            ['senior','Senior Manager','Approves the AML/CTF Program.'],
            ['principal2','Principal / Managing Partner','Overall firm leadership accountability.'],
            ['delegate','Delegate (optional)','For larger firms where compliance tasks are formally delegated.'],
          ].map(([key,title,desc])=>`
            <div class="border border-slate-200 rounded-xl p-4 space-y-3">
              <div>
                <div class="text-sm font-medium text-slate-700">${title}</div>
                <div class="text-xs text-slate-400 mt-0.5">${desc}</div>
              </div>
              <div class="grid grid-cols-2 gap-3">
                <div><label class="text-xs text-slate-500">Full name</label><input id="appt-${key}-name" type="text" class="inp mt-1" value="${(f.appt||{})[key]?.name||''}"></div>
                <div><label class="text-xs text-slate-500">Date appointed</label><input id="appt-${key}-date" type="date" class="inp mt-1" value="${(f.appt||{})[key]?.date||''}"></div>
              </div>
            </div>`).join('')}
        </div>
      </div>

      <button onclick="saveFirm()" class="w-full bg-indigo-600 text-white py-3 rounded-xl font-semibold hover:bg-indigo-700 transition">Save Firm Profile</button>

    </div>`;
}

// ─── ACTIONS ──────────────────────────────────────────────────────────────────
window.fillAllRoles = function() {
  const name = document.getElementById('sole-name')?.value?.trim();
  if (!name) { toast('Enter your name first', 'err'); return; }
  ['amlco','reporting','senior','principal2','delegate'].forEach(k => {
    const el = document.getElementById(`appt-${k}-name`);
    if (el) el.value = name;
  });
};

window.saveFirm = function() {
  const name = document.getElementById('fp-name')?.value?.trim();
  if (!name) { toast('Firm name is required', 'err'); return; }
  S.firm = {
    name, abn: document.getElementById('fp-abn')?.value||'',
    acn: document.getElementById('fp-acn')?.value||'',
    type: document.getElementById('fp-type')?.value||'',
    address: document.getElementById('fp-address')?.value||'',
    suburb: document.getElementById('fp-suburb')?.value||'',
    state: document.getElementById('fp-state')?.value||'',
    postcode: document.getElementById('fp-postcode')?.value||'',
    principal: document.getElementById('fp-principal')?.value||'',
    position: document.getElementById('fp-position')?.value||'',
    email: document.getElementById('fp-email')?.value||'',
    phone: document.getElementById('fp-phone')?.value||'',
    appt: {}
  };
  ['amlco','reporting','senior','principal2','delegate'].forEach(k => {
    S.firm.appt[k] = {
      name: document.getElementById(`appt-${k}-name`)?.value||'',
      date: document.getElementById(`appt-${k}-date`)?.value||''
    };
  });
  save(); toast('Firm profile saved'); go('dashboard');
};
