import { S, save } from '../state/index.js';
import { toast, infoBtn, infoPop } from '../components/index.js';

export function screen() {
  const f = S.firm;
  const isComplete = !!(f.name && f.abn);
  const badge = isComplete
    ? '<span class="inline-flex items-center gap-1 text-xs font-semibold px-3 py-1 rounded-full bg-green-100 text-green-700">✓ Complete</span>'
    : '<span class="inline-flex items-center gap-1 text-xs font-semibold px-3 py-1 rounded-full bg-slate-100 text-slate-500">⚠ Incomplete</span>';

  return `
    <div class="py-8 space-y-8">

      <div class="flex items-start justify-between">
        <div>
          <h1 class="text-2xl font-bold text-slate-900">Firm Profile</h1>
          <p class="text-sm text-slate-400 mt-1">Practice identity and contact details for AUSTRAC and compliance reporting.</p>
        </div>
        ${badge}
      </div>

      <!-- PRACTICE IDENTITY -->
      <div class="bg-white border border-slate-200 rounded-xl p-6 space-y-5">
        <div class="flex items-center gap-2">
          <h2 class="text-sm font-bold text-slate-700">Practice Identity</h2>
          ${infoBtn('firm-practice-tip')}
        </div>
        ${infoPop('firm-practice-tip', `<strong class="text-indigo-300 block mb-2">Why AUSTRAC needs your practice details</strong>
          <p>AUSTRAC and any independent evaluator must be able to clearly identify your firm and know who is ultimately responsible for AML/CTF compliance. Your firm name, ABN, address, and principal contact are the foundation of your compliance record.</p>
          <p class="mt-2">In the event of an audit, inspection, or enforcement action, these details establish: <strong class="text-white">(1)</strong> which legal entity is the reporting entity, <strong class="text-white">(2)</strong> how to contact the firm, and <strong class="text-white">(3)</strong> who the accountable person is.</p>
          <p class="mt-2 text-slate-400 border-t border-slate-600 pt-2">These details appear on every compliance report generated by SimpleAML and must be kept current.</p>`)}
        <div class="space-y-4">
          <div><label class="text-xs text-slate-500">Firm name *</label><input id="fp-name" type="text" class="inp mt-1" value="${f.name||''}" placeholder="e.g. Smith & Associates"></div>
          <div class="grid grid-cols-3 gap-4">
            <div><label class="text-xs text-slate-500">ABN *</label><input id="fp-abn" type="text" class="inp mt-1" value="${f.abn||''}" placeholder="12 345 678 901"></div>
            <div><label class="text-xs text-slate-500">ACN</label><input id="fp-acn" type="text" class="inp mt-1" value="${f.acn||''}" placeholder="Optional"></div>
            <div><label class="text-xs text-slate-500">Practice type</label>
              <select id="fp-type" class="inp mt-1">
                ${['Sole Practitioner','Partnership','Pty Ltd','Trust','Other'].map(o=>`<option ${f.type===o?'selected':''}>${o}</option>`).join('')}
              </select>
            </div>
          </div>
        </div>
      </div>

      <!-- PRACTICE ADDRESS -->
      <div class="bg-white border border-slate-200 rounded-xl p-6 space-y-5">
        <h2 class="text-sm font-bold text-slate-700">Practice Address</h2>
        <div class="space-y-4">
          <div><label class="text-xs text-slate-500">Street address</label><input id="fp-address" type="text" class="inp mt-1" value="${f.address||''}" placeholder="Level 2, 123 Collins St"></div>
          <div class="grid grid-cols-3 gap-4">
            <div><label class="text-xs text-slate-500">Suburb</label><input id="fp-suburb" type="text" class="inp mt-1" value="${f.suburb||''}" placeholder="Melbourne"></div>
            <div><label class="text-xs text-slate-500">State</label>
              <select id="fp-state" class="inp mt-1">
                <option value="">— Select —</option>
                ${['NSW','VIC','QLD','WA','SA','TAS','ACT','NT'].map(o=>`<option ${f.state===o?'selected':''}>${o}</option>`).join('')}
              </select>
            </div>
            <div><label class="text-xs text-slate-500">Postcode</label><input id="fp-postcode" type="text" class="inp mt-1" value="${f.postcode||''}" placeholder="3000"></div>
          </div>
        </div>
      </div>

      <!-- PRINCIPAL CONTACT -->
      <div class="bg-white border border-slate-200 rounded-xl p-6 space-y-5">
        <h2 class="text-sm font-bold text-slate-700">Principal Contact</h2>
        <div class="grid grid-cols-2 gap-4">
          <div><label class="text-xs text-slate-500">Full name *</label><input id="fp-principal" type="text" class="inp mt-1" value="${f.principal||''}" placeholder="Jane Smith"></div>
          <div><label class="text-xs text-slate-500">Position</label><input id="fp-position" type="text" class="inp mt-1" value="${f.position||''}" placeholder="Principal / Managing Partner"></div>
          <div><label class="text-xs text-slate-500">Email *</label><input id="fp-email" type="email" class="inp mt-1" value="${f.email||''}" placeholder="jane@firm.com.au"></div>
          <div><label class="text-xs text-slate-500">Phone</label><input id="fp-phone" type="tel" class="inp mt-1" value="${f.phone||''}" placeholder="03 9123 4567"></div>
        </div>
      </div>

      <!-- POST-SAVE NAVIGATION — shown after first save -->
      ${f.savedDate ? `
      <div class="bg-indigo-50 border border-indigo-200 rounded-xl p-4 space-y-3">
        <div class="text-sm font-semibold text-indigo-800">Firm Profile saved — what would you like to do next?</div>
        <div class="flex flex-col gap-2">
          <button onclick="go('firm-appointments')" class="w-full bg-indigo-600 text-white py-2.5 rounded-xl text-sm font-semibold hover:bg-indigo-700 transition">Continue to Appointments →</button>
          <button onclick="go('dashboard')" class="w-full bg-white border border-slate-200 text-slate-600 py-2.5 rounded-xl text-sm font-semibold hover:bg-slate-50 transition">Return to Action Required</button>
          <a href="https://simpleaml.com.au" target="_blank" rel="noopener" class="w-full text-center bg-white border border-slate-200 text-slate-400 py-2.5 rounded-xl text-sm font-semibold hover:bg-slate-50 transition block">Exit to website ↗</a>
        </div>
      </div>` : `
      <button onclick="saveFirmDetails()" class="w-full bg-indigo-600 text-white py-3 rounded-xl font-semibold hover:bg-indigo-700 transition">Save Firm Profile</button>`}

    </div>`;
}

// ─── ACTIONS ──────────────────────────────────────────────────────────────────
window.saveFirmDetails = function() {
  const name = document.getElementById('fp-name')?.value?.trim();
  if (!name) { toast('Firm name is required', 'err'); return; }
  const email = document.getElementById('fp-email')?.value?.trim();
  if (email && !email.includes('@')) { toast('Email address must contain @', 'err'); return; }
  const isFirstSave = !S.firm.newsletterShown;
  // Preserve existing appointments when saving details
  const existingAppt = S.firm.appt || {};
  S.firm = {
    ...S.firm,
    name,
    abn:       document.getElementById('fp-abn')?.value||'',
    acn:       document.getElementById('fp-acn')?.value||'',
    type:      document.getElementById('fp-type')?.value||'',
    address:   document.getElementById('fp-address')?.value||'',
    suburb:    document.getElementById('fp-suburb')?.value||'',
    state:     document.getElementById('fp-state')?.value||'',
    postcode:  document.getElementById('fp-postcode')?.value||'',
    principal: document.getElementById('fp-principal')?.value||'',
    position:  document.getElementById('fp-position')?.value||'',
    email:     email||'',
    phone:     document.getElementById('fp-phone')?.value||'',
    appt:      existingAppt,
    savedDate: new Date().toISOString().split('T')[0],
  };
  save();
  toast('Firm Profile saved');
  if (isFirstSave && typeof window.showNewsletterModal === 'function') {
    setTimeout(function() { window.showNewsletterModal(); }, 400);
  }
  go('firm-details');
};
